apiVersion: v1
kind: Service
metadata:
    name: kington-nginx
spec:
    ports:
        -   port: 80
            targetPort: 80
            protocol: TCP
            name: http
    selector:
        app: kington-nginx

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: kington-nginx
spec:
    replicas: 1
    selector:
        matchLabels:
            app: kington-nginx
    template:
        metadata:
            labels:
                app: kington-nginx
        spec:
            containers:
                -   name: kington-nginx
                    image: docker.pkg.github.com/extraton/kington/kington-nginx:latest
                    ports: [{containerPort: 80}]
            imagePullSecrets:
                -   name: github-registry
